---
- name: Install packages
  include_tasks: install-packages.yml

- name: Configure dhcpcd
  include_tasks: configure-dhcpcd.yml
  when: configure_routes | default(False)

- name: Configure docker-speedtest-analyser
  include_tasks: configure-docker-speedtest-analyser.yml