---
- hosts: all
  gather_facts: true
  become: true
  environment:
    http_proxy: "{{ web_proxy | default('') }}"
    https_proxy: "{{ web_proxy | default('') }}"
  roles:
    - raspberry_pi_speedtest
